name: Build 360T7

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'true'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo docker image prune -a -f

      - name: Initialization environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev

      - name: Clone source code
        run: |
          git clone --depth 1 https://github.com/hanwckf/immortalwrt-mt798x openwrt
          cd openwrt
          # 添加插件源
          echo 'src-git lucky https://github.com/gdy666/luci-app-lucky.git' >> feeds.conf.default
          echo 'src-git passwall https://github.com/xiaorouji/openwrt-passwall.git' >> feeds.conf.default
          echo 'src-git helloworld https://github.com/fw876/helloworld.git' >> feeds.conf.default
          
          # 核心修复：先拉取代码但不更新索引
          ./scripts/feeds update -a
          
          # 在安装索引前，彻底物理删除报错的文件夹
          find feeds/helloworld/ -name "*rust*" -o -name "*shadow-tls*" -o -name "*tuic-client*" | xargs rm -rf
          
          # 再次更新并正式安装
          ./scripts/feeds update -i
          ./scripts/feeds install -a

      - name: Load Custom Configuration
        run: |
          cd openwrt
          cp -f defconfig/mt7981-ax3000.config .config
          # 修改后台 IP 为 192.168.10.1
          sed -i 's/192.168.1.1/192.168.10.1/g' package/base-files/files/bin/config_generate
          make defconfig

      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@main
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')

      - name: Compile the firmware
        run: |
          cd openwrt
          make -j$(nproc) || make -j1 V=s

      - name: Upload firmware directory
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_360T7_Firmware
          path: openwrt/bin/targets/
